"""empty message

Revision ID: 7531bc51381a
Revises: 0f8e576be2b4
Create Date: 2021-08-16 03:54:35.454884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7531bc51381a'
down_revision = '0f8e576be2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients_data', 'active')
    op.drop_column('patients_data', 'authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients_data', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('patients_data', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
