"""empty message

Revision ID: dd219fd64657
Revises: 7531bc51381a
Create Date: 2021-08-16 04:23:36.416494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd219fd64657'
down_revision = '7531bc51381a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients_data', sa.Column('logdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients_data', 'logdate')
    # ### end Alembic commands ###
